// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cht'
	| 'en'

export type Translation = {
	'Head': {	
		/**
		 * TCP
		 */
		'AppName': string
		/**
		 * Connet Wallet
		 */
		'ConnectWallet': string
	}
	'Home': {	
		/**
		 * TCP Global
		 */
		'AppName': string
		/**
		 * In response to the regulatory requirements of local policies, TCP has closed the use of the old version of the APP, and this page is opened to import the APP data into the TACAPA international version
		 */
		'Title': string
		/**
		 * Account
		 */
		'Account': string
		/**
		 * Please enter the old version APP account
		 */
		'AccountPlaceHolder': string
		/**
		 * Password
		 */
		'Password': string
		/**
		 * Please enter the old version APP password
		 */
		'PasswordPlaceHolder': string
		/**
		 * Import
		 */
		'Import': string
		/**
		 * Start
		 */
		'Start': string
		/**
		 * Previous
		 */
		'Previous': string
		/**
		 * The import function will be closed on March 26, 2022, please complete the import as soon as possible before then
		 */
		'Tips1': string
		/**
		 * We have detected that your current IP is from a country/region that is not supported by the service, please consciously exit this function page
		 */
		'Tips2': string
		/**
		 * Locke Balance
		 */
		'LockeBalance': string
		/**
		 * Assets Balance
		 */
		'AssetsBalance': string
		/**
		 * Change Balance
		 */
		'ChangeBalance': string
		/**
		 * Login
		 */
		'Login': string
		/**
		 * Confirm the data
		 */
		'ConfirmData': string
		/**
		 * Imported
		 */
		'Imported': string
		/**
		 * Import successful
		 */
		'ImportedSuccess': string
	}
	'Postion': {	
		/**
		 * Postion Info
		 */
		'Title': string
		/**
		 * Position Balance
		 */
		'PositionBalance': string
		/**
		 * Add Position
		 */
		'AddPosition': string
		/**
		 * Released balance
		 */
		'ReleasedBalance': string
		/**
		 * Withdrawal
		 */
		'Withdrawal': string
		/**
		 * Number of TCP
		 */
		'NumberOfTCP': string
		/**
		 * Balance
		 */
		'Balance': string
		/**
		 * MAX
		 */
		'MAX': string
		/**
		 * Approve
		 */
		'Approve': string
		/**
		 * Please enter the number of TCP
		 */
		'InputPlaceholder': string
		/**
		 * Please use the invite link to open dapp
		 */
		'InviteLinkPlaceholder': string
	}
	'Interest': {	
		/**
		 * Interest Info
		 */
		'Title': string
		/**
		 * Receive interest
		 */
		'ReceiveInterest': string
		/**
		 * Received interest
		 */
		'ReceivedInterest': string
		/**
		 * Receive
		 */
		'Receive': string
		/**
		 * Reinvest
		 */
		'Reinvest': string
		/**
		 * no interest payable
		 */
		'ReceiveInterestZero': string
	}
	'Community': {	
		/**
		 * Community info
		 */
		'Title': string
		/**
		 * Referral user
		 */
		'ReferralUser': string
		/**
		 * Invite
		 */
		'Invite': string
		/**
		 * Referral reward
		 */
		'ReferralReward': string
		/**
		 * Marker level
		 */
		'MarkerLevel': string
		/**
		 * Marker reward
		 */
		'MarkerReward': string
		/**
		 * scan it
		 */
		'Scanit': string
		/**
		 * or copy link
		 */
		'CopyLink': string
		/**
		 * Copy successfully
		 */
		'CopySuccess': string
		/**
		 * Copy
		 */
		'Copy': string
	}
	'Recharge': {	
		/**
		 * TCP Recharge
		 */
		'Title': string
		/**
		 * position amount
		 */
		'PositionBalance': string
		/**
		 * Add position
		 */
		'AddPosition': string
		/**
		 * Position has been released
		 */
		'ReleasedBalance': string
		/**
		 * Extract
		 */
		'Withdrawal': string
		/**
		 * Number of TCP
		 */
		'NumberOfTCP': string
		/**
		 * Balance
		 */
		'Balance': string
		/**
		 * maximum
		 */
		'MAX': string
		/**
		 * Authorization
		 */
		'Approve': string
		/**
		 * Please enter the number of TCP
		 */
		'InputPlaceholder': string
		/**
		 * Please use the invitation link to open the dapp
		 */
		'InviteLinkPlaceholder': string
		/**
		 * Turnover
		 */
		'Turnover': string
		/**
		 * Quantity
		 */
		'Quantity': string
		/**
		 * Quota
		 */
		'Quota': string
		/**
		 * Safety deposit has been paid
		 */
		'Safety': string
		/**
		 * Allowed to sell
		 */
		'Allowed': string
		/**
		 * Buy
		 */
		'Buy': string
		/**
		 * Unit Price
		 */
		'UnitPrice': string
		/**
		 * Business Nickname
		 */
		'BusinessNickname': string
		/**
		 * Available Balance
		 */
		'AvailableBalance': string
		/**
		 * Need to Pay
		 */
		'NeedToPay': string
		/**
		 * Allowed to use
		 */
		'WithPermission': string
		/**
		 * Warm Tips
		 */
		'KindTips': string
		/**
		 * Kind Tips Content
		 */
		'KindTipsContent': string
		/**
		 * Create Time
		 */
		'CreateTime': string
		/**
		 * Total
		 */
		'LumpSum': string
	}
	'Footer': {	
		/**
		 * Serve
		 */
		'Serve': string
		/**
		 * Help Center
		 */
		'Help': string
		/**
		 * Postion
		 */
		'Postion': string
		/**
		 * Interest
		 */
		'Interest': string
		/**
		 * Community
		 */
		'Community': string
		/**
		 * TCP充值
		 */
		'Recharge': string
	}
	'Btn': {	
		/**
		 * Close
		 */
		'Close': string
		/**
		 * Confirm
		 */
		'Confirm': string
	}
	'Error': {	
		/**
		 * No Ethereum browser extension detected, install MetaMask on desktop or visit from a dApp browser on mobile.
		 */
		'NoEthereumProviderError': string
		/**
		 * You're connected to an unsupported network.
		 */
		'UnsupportedChainIdError': string
		/**
		 * Please authorize this website to access your Ethereum account.
		 */
		'UserRejectedRequestErrorInjected': string
		/**
		 * An unknown error occurred. Check the console for more details.
		 */
		'UnknownError': string
		/**
		 * Account cannot be empty
		 */
		'MobileEmptyError': string
		/**
		 * Account does not exist
		 */
		'MobileNotExistError': string
		/**
		 * Password cannot be empty
		 */
		'PasswordEmptyError': string
		/**
		 * The password is incorrect
		 */
		'PasswordIncorrectError': string
		/**
		 * A wallet address can only be bound to one account
		 */
		'AccountIsUpError': string
	}
}

export type TranslationFunctions = {
	'Head': {	
		/**
		 * TCP
		 */
		'AppName': () => LocalizedString
		/**
		 * Connet Wallet
		 */
		'ConnectWallet': () => LocalizedString
	}
	'Home': {	
		/**
		 * TCP Global
		 */
		'AppName': () => LocalizedString
		/**
		 * In response to the regulatory requirements of local policies, TCP has closed the use of the old version of the APP, and this page is opened to import the APP data into the TACAPA international version
		 */
		'Title': () => LocalizedString
		/**
		 * Account
		 */
		'Account': () => LocalizedString
		/**
		 * Please enter the old version APP account
		 */
		'AccountPlaceHolder': () => LocalizedString
		/**
		 * Password
		 */
		'Password': () => LocalizedString
		/**
		 * Please enter the old version APP password
		 */
		'PasswordPlaceHolder': () => LocalizedString
		/**
		 * Import
		 */
		'Import': () => LocalizedString
		/**
		 * Start
		 */
		'Start': () => LocalizedString
		/**
		 * Previous
		 */
		'Previous': () => LocalizedString
		/**
		 * The import function will be closed on March 26, 2022, please complete the import as soon as possible before then
		 */
		'Tips1': () => LocalizedString
		/**
		 * We have detected that your current IP is from a country/region that is not supported by the service, please consciously exit this function page
		 */
		'Tips2': () => LocalizedString
		/**
		 * Locke Balance
		 */
		'LockeBalance': () => LocalizedString
		/**
		 * Assets Balance
		 */
		'AssetsBalance': () => LocalizedString
		/**
		 * Change Balance
		 */
		'ChangeBalance': () => LocalizedString
		/**
		 * Login
		 */
		'Login': () => LocalizedString
		/**
		 * Confirm the data
		 */
		'ConfirmData': () => LocalizedString
		/**
		 * Imported
		 */
		'Imported': () => LocalizedString
		/**
		 * Import successful
		 */
		'ImportedSuccess': () => LocalizedString
	}
	'Postion': {	
		/**
		 * Postion Info
		 */
		'Title': () => LocalizedString
		/**
		 * Position Balance
		 */
		'PositionBalance': () => LocalizedString
		/**
		 * Add Position
		 */
		'AddPosition': () => LocalizedString
		/**
		 * Released balance
		 */
		'ReleasedBalance': () => LocalizedString
		/**
		 * Withdrawal
		 */
		'Withdrawal': () => LocalizedString
		/**
		 * Number of TCP
		 */
		'NumberOfTCP': () => LocalizedString
		/**
		 * Balance
		 */
		'Balance': () => LocalizedString
		/**
		 * MAX
		 */
		'MAX': () => LocalizedString
		/**
		 * Approve
		 */
		'Approve': () => LocalizedString
		/**
		 * Please enter the number of TCP
		 */
		'InputPlaceholder': () => LocalizedString
		/**
		 * Please use the invite link to open dapp
		 */
		'InviteLinkPlaceholder': () => LocalizedString
	}
	'Interest': {	
		/**
		 * Interest Info
		 */
		'Title': () => LocalizedString
		/**
		 * Receive interest
		 */
		'ReceiveInterest': () => LocalizedString
		/**
		 * Received interest
		 */
		'ReceivedInterest': () => LocalizedString
		/**
		 * Receive
		 */
		'Receive': () => LocalizedString
		/**
		 * Reinvest
		 */
		'Reinvest': () => LocalizedString
		/**
		 * no interest payable
		 */
		'ReceiveInterestZero': () => LocalizedString
	}
	'Community': {	
		/**
		 * Community info
		 */
		'Title': () => LocalizedString
		/**
		 * Referral user
		 */
		'ReferralUser': () => LocalizedString
		/**
		 * Invite
		 */
		'Invite': () => LocalizedString
		/**
		 * Referral reward
		 */
		'ReferralReward': () => LocalizedString
		/**
		 * Marker level
		 */
		'MarkerLevel': () => LocalizedString
		/**
		 * Marker reward
		 */
		'MarkerReward': () => LocalizedString
		/**
		 * scan it
		 */
		'Scanit': () => LocalizedString
		/**
		 * or copy link
		 */
		'CopyLink': () => LocalizedString
		/**
		 * Copy successfully
		 */
		'CopySuccess': () => LocalizedString
		/**
		 * Copy
		 */
		'Copy': () => LocalizedString
	}
	'Recharge': {	
		/**
		 * TCP Recharge
		 */
		'Title': () => LocalizedString
		/**
		 * position amount
		 */
		'PositionBalance': () => LocalizedString
		/**
		 * Add position
		 */
		'AddPosition': () => LocalizedString
		/**
		 * Position has been released
		 */
		'ReleasedBalance': () => LocalizedString
		/**
		 * Extract
		 */
		'Withdrawal': () => LocalizedString
		/**
		 * Number of TCP
		 */
		'NumberOfTCP': () => LocalizedString
		/**
		 * Balance
		 */
		'Balance': () => LocalizedString
		/**
		 * maximum
		 */
		'MAX': () => LocalizedString
		/**
		 * Authorization
		 */
		'Approve': () => LocalizedString
		/**
		 * Please enter the number of TCP
		 */
		'InputPlaceholder': () => LocalizedString
		/**
		 * Please use the invitation link to open the dapp
		 */
		'InviteLinkPlaceholder': () => LocalizedString
		/**
		 * Turnover
		 */
		'Turnover': () => LocalizedString
		/**
		 * Quantity
		 */
		'Quantity': () => LocalizedString
		/**
		 * Quota
		 */
		'Quota': () => LocalizedString
		/**
		 * Safety deposit has been paid
		 */
		'Safety': () => LocalizedString
		/**
		 * Allowed to sell
		 */
		'Allowed': () => LocalizedString
		/**
		 * Buy
		 */
		'Buy': () => LocalizedString
		/**
		 * Unit Price
		 */
		'UnitPrice': () => LocalizedString
		/**
		 * Business Nickname
		 */
		'BusinessNickname': () => LocalizedString
		/**
		 * Available Balance
		 */
		'AvailableBalance': () => LocalizedString
		/**
		 * Need to Pay
		 */
		'NeedToPay': () => LocalizedString
		/**
		 * Allowed to use
		 */
		'WithPermission': () => LocalizedString
		/**
		 * Warm Tips
		 */
		'KindTips': () => LocalizedString
		/**
		 * Kind Tips Content
		 */
		'KindTipsContent': () => LocalizedString
		/**
		 * Create Time
		 */
		'CreateTime': () => LocalizedString
		/**
		 * Total
		 */
		'LumpSum': () => LocalizedString
	}
	'Footer': {	
		/**
		 * Serve
		 */
		'Serve': () => LocalizedString
		/**
		 * Help Center
		 */
		'Help': () => LocalizedString
		/**
		 * Postion
		 */
		'Postion': () => LocalizedString
		/**
		 * Interest
		 */
		'Interest': () => LocalizedString
		/**
		 * Community
		 */
		'Community': () => LocalizedString
		/**
		 * TCP充值
		 */
		'Recharge': () => LocalizedString
	}
	'Btn': {	
		/**
		 * Close
		 */
		'Close': () => LocalizedString
		/**
		 * Confirm
		 */
		'Confirm': () => LocalizedString
	}
	'Error': {	
		/**
		 * No Ethereum browser extension detected, install MetaMask on desktop or visit from a dApp browser on mobile.
		 */
		'NoEthereumProviderError': () => LocalizedString
		/**
		 * You're connected to an unsupported network.
		 */
		'UnsupportedChainIdError': () => LocalizedString
		/**
		 * Please authorize this website to access your Ethereum account.
		 */
		'UserRejectedRequestErrorInjected': () => LocalizedString
		/**
		 * An unknown error occurred. Check the console for more details.
		 */
		'UnknownError': () => LocalizedString
		/**
		 * Account cannot be empty
		 */
		'MobileEmptyError': () => LocalizedString
		/**
		 * Account does not exist
		 */
		'MobileNotExistError': () => LocalizedString
		/**
		 * Password cannot be empty
		 */
		'PasswordEmptyError': () => LocalizedString
		/**
		 * The password is incorrect
		 */
		'PasswordIncorrectError': () => LocalizedString
		/**
		 * A wallet address can only be bound to one account
		 */
		'AccountIsUpError': () => LocalizedString
	}
}

export type Formatters = {}
